### ISSUE TITLE
invert sorting?

### ISSUE THREAD

**Issue by iraklis10** [michaelkaye/local-buses#1]
Incredibly useful and thanks for writing and hosting this first of all. Would it be possible to invert the sorting of the results? What is the point of having the slowest bus first on the list? Thanks!

**Comment by michaelkaye** [comment]
So generally I use it to find when to leave - with further out stops you only get about 3-4 buses, and the options were to leave in 20min or 10 min or run - so it would all just sit on a page.

I didn't want to put the impossible-to-get buses on the top of the page, (as you'd get with fastest buses first), and having some sort of "fastest possible to slowest possible, then all the ones you can't get if you left home now" sorting seemed ... wrong.

Probably we could add a sort order parameter if it's something that actually would be of use

**Comment by iraklis10** [comment]
Now that you give your rationale I can see how it makes perfect sense. It is a feature not a bug! 

It is still incredibly useful for my application as it is, so grateful for sharing. In my case, all 3 bus stops are very close to each other (plus not too far from where I am) i.e. identical walking times, so essentially I was looking to combine all timetables into one.
